### ISSUE TITLE
[Bug] Infinite loop on the webpack 5 example

### ISSUE THREAD

**Issue by kbariotis** [sysgears/webpack-virtual-modules#83] opened 2020-12-17 20:38 UTC
- [ ] I'd be willing to submit the fix

**Describe the bug**

When running the webpack 5 example, there is an endless loop with webpack compiling the same files again and again.

**To Reproduce**

Just run the webpack 5 example.

**Screenshots**
![image](https://user-images.githubusercontent.com/605742/102540937-ae204a80-40a7-11eb-9d4d-7878bf6800b9.png)

**Environment if relevant (please complete the following information):**

 - OS: OSX Big Sur
 - Node version 14
 - Mochapack version NA
 - Webpack version 5

**Comment by stevenpetryk** [comment] 2020-12-23 23:41
I found a gross workaround. You can compare webpack's filesystem with the incoming changes you want to write to your module, and bail out if they're the same:

```js
const modulePath = "<YOUR MODULE'S *ABSOLUTE* PATH>"
const moduleContents = "<YOUR MODULE'S CONTENTS>"

let finalInputFileSystem = compiler.inputFileSystem;
while (finalInputFileSystem && finalInputFileSystem._inputFileSystem) {
  finalInputFileSystem = finalInputFileSystem._inputFileSystem;
}

const existing = finalInputFileSystem._virtualFiles[modulePath];
if (existing.contents != moduleContents) {
  virtualModules.writeModule(modulePath, moduleContents);
}
```

**Comment by stevenpetryk** [comment] 2020-12-23 23:45
So maybe the fix here would just be that `webpack-virtual-modules` needs to ignore calls to `writeModule` when they wouldn't change the module.

**Comment by larixer** [comment] 2020-12-24 07:28
@stevenpetryk This comparison should be done on caller side. `wrtieModule` is expected to match the behaviour of `fs.writeFile`, e.g. when you write the same contents the file timestamp should be updated and recompilation should be scheduled. It is a bug in the example

**Comment by larixer** [comment] 2021-03-05 08:24
Closing as works as intended, we also have #89 which tells about the opposite intended behaviour. And only one behaviour from these two can exists, because they are in direct contradiction to each another.

**Closed by larixer** 2021-03-05 08:24 UTC
Labels: invalid

**Comment by larixer** [comment] 2021-08-13 06:49
@atesgoral 

> > It is a bug in the example
> 
> I assume the said bug is still there? Running the webpack 5 example, I see an infinite compilation loop.

Yes, it is still present in the example.

**Comment by chaddjohnson** [comment] 2022-09-12 01:44
This still appears to be an issue. Seems to happen with [`@shopify/web-worker/webpack`](https://github.com/Shopify/quilt/blob/main/packages/web-worker/src/webpack-parts/plugin.ts) which uses webpack-virtual-modules. Happens when using webpack-dev-server.

**Comment by borayuksel1903** [comment] 2022-09-16 22:11
We are using this API on our end, and are seeing this infinite loop issue still. Opening a PR for a potential fix, but open to other suggestions. I don't think this and #89 need to be conflicting, we could hopefully have both issues fixed.
